/**
 * Database-driven roles and permissions
 * Generated on: 2026-02-12T07:10:36.596Z
 *
 * This file contains roles and permissions pulled from the Supabase database.
 * Use these as defaults instead of the hardcoded values in lib/rbac/types.ts
 */

import { Role, Permission } from "./types"

export const DATABASE_DEFAULT_ROLES: Role[] = [
  {
    id: "00000000-0000-0000-0000-000000000000",
    name: "super-admin",
    displayName: "super-admin",
    description: "Super Administrator with highest privileges, can create admin roles",
    level: 1,
    permissions: [
      "entries.create",
      "entries.read",
      "entries.update",
      "entries.delete",
      "entries.export",
      "entries.import",
      "users.create",
      "users.read",
      "users.update",
      "users.delete",
      "entries.export.own",
      "entries.delete.own",
      "users.manage",
      "departments.create",
      "departments.read",
      "departments.update",
      "departments.delete",
      "departments.members.read",
      "departments.members.manage",
      "analytics.read",
      "analytics.read.own",
      "analytics.advanced",
      "analytics.team",
      "admin.system",
      "admin.audit",
      "admin.backup",
      "admin.restore",
      "admin.settings",
      "department_questions.answer",
      "department_questions.read",
    ],
    accessScopes: [
      "scope-system-admin",
      "scope-team-operations",
      "scope-delivery-engineering",
      "scope-quality-assurance",
      "scope-support-operations",
      "scope-creative-studio",
      "scope-observability",
    ],
    isSystem: true,
    createdAt: "2026-01-15T12:07:19.326004+00:00",
    updatedAt: "2026-01-15T12:07:19.326004+00:00",
  },
  {
    id: "00000000-0000-0000-0000-000000000002",
    name: "user",
    displayName: "user",
    description: "Standard user",
    level: 2,
    permissions: ["entries.create", "entries.read", "entries.update", "entries.delete", "entries.export"],
    accessScopes: ["scope-observability"],
    isSystem: true,
    createdAt: "2025-11-14T01:30:25.818795+00:00",
    updatedAt: "2025-11-28T12:53:32.474174+00:00",
  },
  {
    id: "00000000-0000-0000-0000-000000000001",
    name: "admin",
    displayName: "admin",
    description: "Administrator (highest privilege)",
    level: 4,
    permissions: [
      "entries.create",
      "entries.read",
      "entries.update",
      "entries.delete",
      "entries.export",
      "entries.import",
      "users.create",
      "users.read",
      "users.update",
      "users.delete",
      "entries.export.own",
      "entries.delete.own",
      "users.manage",
      "departments.create",
      "departments.read",
      "departments.update",
      "departments.delete",
      "departments.members.read",
      "departments.members.manage",
      "analytics.read",
      "analytics.read.own",
      "analytics.advanced",
      "analytics.team",
      "admin.system",
      "admin.audit",
      "admin.backup",
      "admin.restore",
      "admin.settings",
      "department_questions.answer",
      "department_questions.read",
    ],
    accessScopes: [
      "scope-system-admin",
      "scope-team-operations",
      "scope-delivery-engineering",
      "scope-quality-assurance",
      "scope-support-operations",
      "scope-creative-studio",
      "scope-observability",
    ],
    isSystem: true,
    createdAt: "2025-11-14T01:30:25.818795+00:00",
    updatedAt: "2026-01-10T07:24:17.453669+00:00",
  },
  {
    id: "00000000-0000-0000-0000-000000000010",
    name: "system-admin",
    displayName: "system-admin",
    description: "System administrator (same privileges as admin)",
    level: 5,
    permissions: [
      "entries.create",
      "entries.read",
      "entries.update",
      "entries.delete",
      "entries.export",
      "entries.import",
      "users.create",
      "users.read",
      "users.update",
      "users.delete",
      "entries.export.own",
      "entries.delete.own",
      "users.manage",
      "departments.create",
      "departments.read",
      "departments.update",
      "departments.delete",
      "departments.members.read",
      "departments.members.manage",
      "analytics.read",
      "analytics.read.own",
      "analytics.advanced",
      "analytics.team",
      "admin.system",
      "admin.audit",
      "admin.backup",
      "admin.restore",
      "admin.settings",
      "department_questions.answer",
      "department_questions.read",
    ],
    accessScopes: [
      "scope-system-admin",
      "scope-team-operations",
      "scope-delivery-engineering",
      "scope-quality-assurance",
      "scope-support-operations",
      "scope-creative-studio",
      "scope-observability",
    ],
    isSystem: true,
    createdAt: "2026-01-15T12:38:20.160614+00:00",
    updatedAt: "2026-01-15T12:38:20.160614+00:00",
  },
]

export const DATABASE_DEFAULT_PERMISSIONS: Permission[] = [
  {
    id: "7e8268fe-792d-4a62-b58d-842a3f271693",
    name: "entries.create",
    resource: "entries",
    action: "create",
    description: "entries create",
    category: "read",
  },
  {
    id: "ccbfdeec-2860-4944-bd3d-7c72ee87f42a",
    name: "entries.read",
    resource: "entries",
    action: "read",
    description: "entries read",
    category: "read",
  },
  {
    id: "e5a82d6e-b62b-494e-82a9-27ba81dea5da",
    name: "entries.update",
    resource: "entries",
    action: "update",
    description: "entries update",
    category: "read",
  },
  {
    id: "b4d8c417-6a26-4592-ab38-f7a428004fac",
    name: "entries.delete",
    resource: "entries",
    action: "delete",
    description: "entries delete",
    category: "read",
  },
  {
    id: "1640d86b-fec0-4e88-ace5-e828b72f1c3b",
    name: "entries.export",
    resource: "entries",
    action: "export",
    description: "entries export",
    category: "read",
  },
  {
    id: "8a3f75d5-a974-42b7-8c34-a6712009e27d",
    name: "entries.import",
    resource: "entries",
    action: "import",
    description: "entries import",
    category: "read",
  },
  {
    id: "397d3df7-ac29-4985-bf16-3a7887d570eb",
    name: "users.create",
    resource: "users",
    action: "create",
    description: "users create",
    category: "read",
  },
  {
    id: "54d90015-ffc9-4d93-a636-2d33a9c82c22",
    name: "users.read",
    resource: "users",
    action: "read",
    description: "users read",
    category: "read",
  },
  {
    id: "ad541c2a-8879-4a61-bc82-15e979f1f505",
    name: "users.update",
    resource: "users",
    action: "update",
    description: "users update",
    category: "read",
  },
  {
    id: "100c03f3-5b97-453a-ac5e-5a6790b43735",
    name: "users.delete",
    resource: "users",
    action: "delete",
    description: "users delete",
    category: "read",
  },
  {
    id: "54a82dcb-cd5f-43ce-a7e3-31dd33fd1a18",
    name: "entries.export.own",
    resource: "entries",
    action: "export.own",
    description: "entries export.own",
    category: "read",
  },
  {
    id: "2a39d2ae-464b-4f39-aead-dd17239b9fe4",
    name: "entries.delete.own",
    resource: "entries",
    action: "delete.own",
    description: "entries delete.own",
    category: "read",
  },
  {
    id: "d64e690f-defd-4512-89ca-15cad8010102",
    name: "users.manage",
    resource: "users",
    action: "manage",
    description: "users manage",
    category: "read",
  },
  {
    id: "8b66e51d-41d6-4b5a-90d4-5359528ee890",
    name: "departments.create",
    resource: "departments",
    action: "create",
    description: "departments create",
    category: "read",
  },
  {
    id: "a7edea60-7d49-456f-9870-50449b9d6862",
    name: "departments.read",
    resource: "departments",
    action: "read",
    description: "departments read",
    category: "read",
  },
  {
    id: "68c8d432-8a4b-4a50-a64a-be942ba160fe",
    name: "departments.update",
    resource: "departments",
    action: "update",
    description: "departments update",
    category: "read",
  },
  {
    id: "0085c9c9-9023-48e1-a652-70e3016dd587",
    name: "departments.delete",
    resource: "departments",
    action: "delete",
    description: "departments delete",
    category: "read",
  },
  {
    id: "daf0a1b3-3eb2-467f-9fad-123842d11d8c",
    name: "departments.members.read",
    resource: "departments",
    action: "members.read",
    description: "departments members.read",
    category: "read",
  },
  {
    id: "13ecb8d4-29cc-4c9e-bcff-bca2ee3f5637",
    name: "departments.members.manage",
    resource: "departments",
    action: "members.manage",
    description: "departments members.manage",
    category: "read",
  },
  {
    id: "18241380-e0c2-441e-8883-07e7900ddbb1",
    name: "analytics.read",
    resource: "analytics",
    action: "read",
    description: "analytics read",
    category: "read",
  },
  {
    id: "1b0dfe28-f094-4e94-818c-bcab969d96cf",
    name: "analytics.read.own",
    resource: "analytics",
    action: "read.own",
    description: "analytics read.own",
    category: "read",
  },
  {
    id: "9b35ae03-3b57-432f-976c-1dfda653ca2a",
    name: "analytics.advanced",
    resource: "analytics",
    action: "advanced",
    description: "analytics advanced",
    category: "read",
  },
  {
    id: "f273b588-520b-4f1d-9ece-fcc427fc4297",
    name: "analytics.team",
    resource: "analytics",
    action: "team",
    description: "analytics team",
    category: "read",
  },
  {
    id: "43803400-f326-48ec-a59b-22abb171a4a0",
    name: "admin.system",
    resource: "admin",
    action: "system",
    description: "admin system",
    category: "read",
  },
  {
    id: "9bf59d39-f298-46b5-a266-8c5b84917d27",
    name: "admin.audit",
    resource: "admin",
    action: "audit",
    description: "admin audit",
    category: "read",
  },
  {
    id: "4699edd4-2b47-43ae-af3c-35f9a8b8b367",
    name: "admin.backup",
    resource: "admin",
    action: "backup",
    description: "admin backup",
    category: "read",
  },
  {
    id: "c0f94be1-0383-468e-a866-64bf7e7eee65",
    name: "admin.restore",
    resource: "admin",
    action: "restore",
    description: "admin restore",
    category: "read",
  },
  {
    id: "962f75f4-cf9a-4c9d-be29-0c026abe8c82",
    name: "admin.settings",
    resource: "admin",
    action: "settings",
    description: "admin settings",
    category: "read",
  },
  {
    id: "3dfe3b1f-2cc7-4e2e-bfd9-5175eac653e0",
    name: "department_questions.answer",
    resource: "department_questions",
    action: "answer",
    description: "department_questions answer",
    category: "read",
  },
  {
    id: "196e0b46-367b-418b-8f77-dbdc6ce1aa13",
    name: "department_questions.read",
    resource: "department_questions",
    action: "read",
    description: "department_questions read",
    category: "read",
  },
]

// Helper function to merge database defaults with fallback defaults
export function getRolesWithFallback(databaseRoles: Role[] = []): Role[] {
  if (databaseRoles.length > 0) {
    return databaseRoles
  }
  console.warn("⚠️  No roles found in database, falling back to database defaults")
  return DATABASE_DEFAULT_ROLES
}

export function getPermissionsWithFallback(databasePermissions: Permission[] = []): Permission[] {
  if (databasePermissions.length > 0) {
    return databasePermissions
  }
  console.warn("⚠️  No permissions found in database, falling back to database defaults")
  return DATABASE_DEFAULT_PERMISSIONS
}
