declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SUPABASE_URL: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string
    SUPABASE_URL: string
    SUPABASE_SERVICE_ROLE_KEY: string
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME?: string
    NEXT_PUBLIC_CLOUDINARY_API_KEY?: string
    CLOUDINARY_API_SECRET?: string
    CLOUDINARY_UPLOAD_FOLDER?: string
    NEXT_PUBLIC_FF_ANALYTICS?: string
    FF_ANALYTICS?: string
    NEXT_PUBLIC_FF_SELF_SERVICE_AUTH?: string
    FF_SELF_SERVICE_AUTH?: string
    NEXT_PUBLIC_FF_DEPARTMENTS?: string
    FF_DEPARTMENTS?: string
    NEXT_PUBLIC_FF_ADMIN_NOTIFICATIONS?: string
    FF_ADMIN_NOTIFICATIONS?: string
    NEXT_PUBLIC_FF_ADMIN_PERMISSIONS?: string
    FF_ADMIN_PERMISSIONS?: string
    NEXT_PUBLIC_FF_ADMIN_ROLE_AND_ACCESS?: string
    FF_ADMIN_ROLE_AND_ACCESS?: string
  }
}
